<?php

$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if(isset($form)): ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('home', array('action' => 'addreview')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('userId'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('text'));
echo $this->formRow($form->get('rating'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<?php endif; ?>

<?php if(isset($message)): ?>
    <?php echo $message ?>
<?php endif; ?>