<?php

$title = 'Add new user';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('home', array('action' => 'adduser')));
$form->prepare();

echo $this->form()->openTag($form);
/*echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('email'));
echo $this->form($form->get('rights'));*/
echo $this->formCollection($form);
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();